"""Sandbox setting definitions: Sandbox platform, Skills, Code Interpreter."""

from __future__ import annotations

from src.kernel.config.docker_sandbox import DOCKER_SANDBOX_DEFAULTS, DOCKER_SANDBOX_OPTIONS
from src.kernel.schemas.setting import SettingCategory, SettingType

SANDBOX_SETTING_DEFINITIONS: dict[str, dict] = {
    # ============================================
    # Sandbox Settings
    # ============================================
    "ENABLE_SANDBOX": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.SANDBOX,
        "subcategory": "general",
        "description": "settingDesc.ENABLE_SANDBOX",
        "default": False,
        "frontend_visible": True,
    },
    "SANDBOX_PLATFORM": {
        "type": SettingType.SELECT,
        "category": SettingCategory.SANDBOX,
        "subcategory": "general",
        "description": "settingDesc.SANDBOX_PLATFORM",
        "default": "daytona",
        "depends_on": "ENABLE_SANDBOX",
        "options": ["daytona", "e2b", "cubesandbox", "docker"],
    },
    "DOCKER_SANDBOX_NAMESPACE": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_NAMESPACE",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_NAMESPACE"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DOCKER_SANDBOX_IMAGE": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_IMAGE",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_IMAGE"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DOCKER_SANDBOX_TIMEOUT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_TIMEOUT",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_TIMEOUT"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DOCKER_SANDBOX_IDLE_TIMEOUT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_IDLE_TIMEOUT",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_IDLE_TIMEOUT"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DOCKER_SANDBOX_CLEANUP_INTERVAL": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_CLEANUP_INTERVAL",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_CLEANUP_INTERVAL"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DOCKER_SANDBOX_MAX_CONTAINERS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_MAX_CONTAINERS",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_MAX_CONTAINERS"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DOCKER_SANDBOX_MEMORY_LIMIT_MB": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_MEMORY_LIMIT_MB",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_MEMORY_LIMIT_MB"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DOCKER_SANDBOX_CPU_LIMIT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_CPU_LIMIT",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_CPU_LIMIT"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DOCKER_SANDBOX_PIDS_LIMIT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_PIDS_LIMIT",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_PIDS_LIMIT"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DOCKER_SANDBOX_NETWORK_MODE": {
        "type": SettingType.SELECT,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_NETWORK_MODE",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_NETWORK_MODE"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
        "options": DOCKER_SANDBOX_OPTIONS["DOCKER_SANDBOX_NETWORK_MODE"],
    },
    "DOCKER_SANDBOX_MAX_OUTPUT_BYTES": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "docker",
        "description": "settingDesc.DOCKER_SANDBOX_MAX_OUTPUT_BYTES",
        "default": DOCKER_SANDBOX_DEFAULTS["DOCKER_SANDBOX_MAX_OUTPUT_BYTES"],
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "docker"},
    },
    "DAYTONA_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "daytona",
        "description": "settingDesc.DAYTONA_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "daytona"},
    },
    "DAYTONA_SERVER_URL": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "daytona",
        "description": "settingDesc.DAYTONA_SERVER_URL",
        "default": "",
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "daytona"},
    },
    "DAYTONA_TIMEOUT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "daytona",
        "description": "settingDesc.DAYTONA_TIMEOUT",
        "default": 180,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "daytona"},
    },
    "SANDBOX_GREP_TIMEOUT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "general",
        "description": "settingDesc.SANDBOX_GREP_TIMEOUT",
        "default": 30,
        "depends_on": "ENABLE_SANDBOX",
    },
    "DAYTONA_IMAGE": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "daytona",
        "description": "settingDesc.DAYTONA_IMAGE",
        "default": "",
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "daytona"},
    },
    "DAYTONA_AUTO_STOP_INTERVAL": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "daytona",
        "description": "settingDesc.DAYTONA_AUTO_STOP_INTERVAL",
        "default": 5,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "daytona"},
    },
    "DAYTONA_AUTO_ARCHIVE_INTERVAL": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "daytona",
        "description": "settingDesc.DAYTONA_AUTO_ARCHIVE_INTERVAL",
        "default": 5,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "daytona"},
    },
    "DAYTONA_AUTO_DELETE_INTERVAL": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "daytona",
        "description": "settingDesc.DAYTONA_AUTO_DELETE_INTERVAL",
        "default": 1440,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "daytona"},
    },
    "E2B_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "e2b",
        "description": "settingDesc.E2B_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "e2b"},
    },
    "E2B_TEMPLATE": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "e2b",
        "description": "settingDesc.E2B_TEMPLATE",
        "default": "base",
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "e2b"},
    },
    "E2B_TIMEOUT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "e2b",
        "description": "settingDesc.E2B_TIMEOUT",
        "default": 3600,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "e2b"},
    },
    "E2B_AUTO_PAUSE": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.SANDBOX,
        "subcategory": "e2b",
        "description": "settingDesc.E2B_AUTO_PAUSE",
        "default": True,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "e2b"},
    },
    "E2B_AUTO_RESUME": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.SANDBOX,
        "subcategory": "e2b",
        "description": "settingDesc.E2B_AUTO_RESUME",
        "default": True,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "e2b"},
    },
    "CUBE_API_URL": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "cubesandbox",
        "description": "settingDesc.CUBE_API_URL",
        "default": "http://127.0.0.1:3000",
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "cubesandbox"},
    },
    "CUBE_TEMPLATE": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "cubesandbox",
        "description": "settingDesc.CUBE_TEMPLATE",
        "default": "",
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "cubesandbox"},
    },
    "CUBE_TIMEOUT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "cubesandbox",
        "description": "settingDesc.CUBE_TIMEOUT",
        "default": 3600,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "cubesandbox"},
    },
    "CUBE_PROXY_NODE_IP": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "cubesandbox",
        "description": "settingDesc.CUBE_PROXY_NODE_IP",
        "default": "",
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "cubesandbox"},
    },
    "CUBE_PROXY_PORT_HTTP": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "cubesandbox",
        "description": "settingDesc.CUBE_PROXY_PORT_HTTP",
        "default": 80,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "cubesandbox"},
    },
    "CUBE_SANDBOX_DOMAIN": {
        "type": SettingType.STRING,
        "category": SettingCategory.SANDBOX,
        "subcategory": "cubesandbox",
        "description": "settingDesc.CUBE_SANDBOX_DOMAIN",
        "default": "cube.app",
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "cubesandbox"},
    },
    "CUBE_REQUEST_TIMEOUT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.SANDBOX,
        "subcategory": "cubesandbox",
        "description": "settingDesc.CUBE_REQUEST_TIMEOUT",
        "default": 120,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "cubesandbox"},
    },
    "CUBE_AUTO_PAUSE": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.SANDBOX,
        "subcategory": "cubesandbox",
        "description": "settingDesc.CUBE_AUTO_PAUSE",
        "default": True,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "cubesandbox"},
    },
    "CUBE_AUTO_RESUME": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.SANDBOX,
        "subcategory": "cubesandbox",
        "description": "settingDesc.CUBE_AUTO_RESUME",
        "default": True,
        "depends_on": {"key": "SANDBOX_PLATFORM", "value": "cubesandbox"},
    },
    # ============================================
    # Skills Settings
    # ============================================
    "ENABLE_SKILLS": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.SKILLS,
        "subcategory": "general",
        "description": "settingDesc.ENABLE_SKILLS",
        "default": True,
        "frontend_visible": True,
    },
    # ============================================
    # Code Interpreter Settings
    # ============================================
    "ENABLE_CODE_INTERPRETER": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.TOOLS,
        "subcategory": "code",
        "description": "settingDesc.ENABLE_CODE_INTERPRETER",
        "default": False,
        "frontend_visible": True,
    },
}
