"""
Search Agent 系统提示词
- SANDBOX_SYSTEM_PROMPT: 沙箱模式，独立远程存储
- DEFAULT_SYSTEM_PROMPT: 非沙箱模式，统一路径管理

角色身份通过 SectionPromptMiddleware 独立注入（见 persona.py），
基础提示词只包含能力描述。
"""

from src.agents.core.prompt_policy import (
    LAZY_SANDBOX_RUNTIME_POLICY,
    PERSISTENT_STORAGE_POLICY,
    SANDBOX_STORAGE_POLICY,
)

SANDBOX_SYSTEM_PROMPT = SANDBOX_STORAGE_POLICY
SANDBOX_RUNTIME_SECTION = LAZY_SANDBOX_RUNTIME_POLICY
DEFAULT_SYSTEM_PROMPT = PERSISTENT_STORAGE_POLICY

DEFERRED_TOOL_GUIDE = ""
